KEH-2460 - Concourse IAM Refactor (#76)
* refactor(concourse): use IAM role instead of user

- Also removes unused tf vars

* docs(README): add Concourse instructions

* fix: remove alert when accessing projects to only if there's an error

* chore: bump deps

* refactor(concourse): redeploy api using IAM role instead of user

* chore: update tfvars examples

diff --git a/concourse/ci.yml b/concourse/ci.yml
--- a/concourse/ci.yml
+++ b/concourse/ci.yml
@@ -46,6 +46,7 @@ terraform-task: &terraform-task
     params:
       secrets: ((sdp_((env))_secrets_tat_ui))
       github_access_token: ((github_access_token))
+      aws_role_arn: arn:aws:iam::((aws_account_sdp_((env)))):role/sdp-concourse-((env))
       env: ((env))
       branch: ((branch))
     run:
@@ -65,7 +66,9 @@ terraform-task: &terraform-task
             echo "ERROR: Tag '$tag' is not in semantic versioning format (vX.Y.Z)"
             exit 1
           fi
+          chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
           chmod u+x ./resource-repo/concourse/scripts/terraform_infra.sh
+          source ./resource-repo/concourse/scripts/assume_role.sh
           ./resource-repo/concourse/scripts/terraform_infra.sh
     timeout: 30m
 
@@ -82,14 +85,30 @@ re-deploy-api-task: &redeploy_api
       - name: resource-repo
     params:
       env: ((env))
+      aws_role_arn: ((aws_role_arn))
     run:
       path: sh
       args:
         - -cx
         - |
+          if [ -z "${aws_role_arn:-}" ]; then
+            echo "Error: aws_role_arn is not set."
+            exit 1
+          fi
+
+          aws sts assume-role --output text \
+            --role-arn "${aws_role_arn}" \
+            --role-session-name concourse-pipeline-run \
+            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" |
+            awk -F '\t' '{print $1 > ("AccessKeyId")}{print $2 > ("SecretAccessKey")}{print $3 > ("SessionToken")}'
+
+          export AWS_ACCESS_KEY_ID="$(cat AccessKeyId)"
+          export AWS_SECRET_ACCESS_KEY="$(cat SecretAccessKey)"
+          export AWS_SESSION_TOKEN="$(cat SessionToken)"
+
           # Redeploy API after infrastructure changes
           chmod u+x resource-repo/concourse/scripts/redeploy_api.sh
-          ./resource-repo/concourse/scripts/redeploy_api.sh
+          resource-repo/concourse/scripts/redeploy_api.sh
     timeout: 30m
 
 notify-azure-webhook-task: &notify-azure-webhook-task
@@ -259,7 +278,7 @@ jobs:
       - <<: *redeploy_api
         params:
           env: dev
-          secrets: ((sdp_dev_secrets_tat_ui))
+          aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
     on_failure:
       do:
         - task: notify-azure-webhook
@@ -325,7 +344,7 @@ jobs:
       - <<: *redeploy_api
         params:
           env: prod
-          secrets: ((sdp_prod_secrets_tat_ui))
+          aws_role_arn: arn:aws:iam::((aws_account_sdp_prod)):role/sdp-concourse-prod
     on_failure:
       do:
         - task: notify-azure-webhook
